[env:lilygo-a7670g-s3-standard]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
board_build.mcu        = esp32s3
board_build.f_cpu      = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DBOARD_LILYGO_A7670G_S3_STANDARD
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1   ; routes Serial to USB-CDC on S3

lib_deps =
    vshymanskyy/TinyGSM @ ^0.11.7
    bblanchon/ArduinoJson @ ^7.0.0
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
